// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class CapabilityHandshakeWelcomeEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 1;

        [Key(1)]
        public string SessionId { get; set; } = string.Empty;

        [Key(2)]
        public string ServerName { get; set; } = string.Empty;

        [Key(3)]
        public int SelectedSchemaVersion { get; set; } = 1;

        [Key(4)]
        public DebugStudioCapability ServerCapabilities { get; set; } = DebugStudioCapability.None;

        [Key(5)]
        public DebugStudioCapability NegotiatedCapabilities { get; set; } = DebugStudioCapability.None;

        [Key(6)]
        public int[] SupportedMessageTypes { get; set; } = System.Array.Empty<int>();

        [Key(7)]
        public long TimestampUnixTimeMilliseconds { get; set; }

        [Key(8)]
        public string StatusMessage { get; set; } = string.Empty;

        [Key(9)]
        public string BuildVersion { get; set; } = string.Empty;

        [Key(10)]
        public string Platform { get; set; } = string.Empty;

        [Key(11)]
        public string DeviceModel { get; set; } = string.Empty;

        [Key(12)]
        public string OsVersion { get; set; } = string.Empty;

        [Key(13)]
        public string EngineVersion { get; set; } = string.Empty;

    }
}
