// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class CapabilityHandshakeHelloEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 1;

        [Key(1)]
        public string ClientName { get; set; } = string.Empty;

        [Key(2)]
        public string ClientInstanceId { get; set; } = string.Empty;

        [Key(3)]
        public int MinSchemaVersion { get; set; } = 1;

        [Key(4)]
        public int MaxSchemaVersion { get; set; } = 1;

        [Key(5)]
        public DebugStudioCapability SupportedCapabilities { get; set; } = DebugStudioCapability.None;

        [Key(6)]
        public int[] SupportedMessageTypes { get; set; } = System.Array.Empty<int>();

    }
}
