// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class DebugTelemetryEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 3;

        [Key(1)]
        public long TraceId { get; set; }

        [Key(2)]
        public long SpanId { get; set; }

        [Key(3)]
        public long ParentSpanId { get; set; }

        [Key(4)]
        public string Name { get; set; } = string.Empty;

        [Key(5)]
        public long StartTimestampUtcTicks { get; set; }

        [Key(6)]
        public long EndTimestampUtcTicks { get; set; }

        [Key(7)]
        public double ElapsedMs { get; set; }

        [Key(8)]
        public bool IsSuccess { get; set; }

        [Key(9)]
        public int Level { get; set; }

        [Key(10)]
        public int? TagBits { get; set; }

        [Key(11)]
        public float CpuTime { get; set; }

        [Key(12)]
        public float GpuTime { get; set; }

        [Key(13)]
        public long ManagedMem { get; set; }

        [Key(14)]
        public long NativeMem { get; set; }

        [Key(15)]
        public int SceneFrom { get; set; } = -1;

        [Key(16)]
        public int SceneTo { get; set; } = -1;

        [Key(17)]
        public int CameraTotalViewCount { get; set; } = -1;

        [Key(18)]
        public int CameraAdditionalViewCount { get; set; } = -1;

        [Key(19)]
        public int CameraBlendingViewCount { get; set; } = -1;

        [Key(20)]
        public int CameraMaxStackDepthTotal { get; set; } = -1;

        [Key(21)]
        public int CameraViewId { get; set; } = -1;

        [Key(22)]
        public int CameraActiveCameraHash { get; set; } = -1;

        [Key(23)]
        public string SessionId { get; set; } = string.Empty;

        [Key(24)]
        public long ProducerSequence { get; set; }

        [Key(25)]
        public int? UnityFrameAtStart { get; set; }

        [Key(26)]
        public int? UnityFrameAtEnd { get; set; }

        [Key(27)]
        public string Kind { get; set; } = "span";

        [Key(28)]
        public DebugTelemetryPayloadV1? Payload { get; set; }

    }
}
