// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class DebugTelemetryPayloadV1
    {
        [Key(0)]
        public byte Shape { get; set; }

        [Key(1)]
        public string? TargetIdentity { get; set; }

        [Key(2)]
        public string? Stage { get; set; }

        [Key(3)]
        public long? ManagedBeforeBytes { get; set; }

        [Key(4)]
        public long? NativeBeforeBytes { get; set; }

        [Key(5)]
        public long? ManagedAfterBytes { get; set; }

        [Key(6)]
        public long? NativeAfterBytes { get; set; }

        [Key(7)]
        public long? ManagedDeltaBytes { get; set; }

        [Key(8)]
        public long? NativeDeltaBytes { get; set; }

        [Key(9)]
        public float? Fps { get; set; }

        [Key(10)]
        public float? CpuMs { get; set; }

        [Key(11)]
        public float? GpuMs { get; set; }

        [Key(12)]
        public bool? GpuAvailable { get; set; }

        [Key(13)]
        public long? ManagedBytes { get; set; }

        [Key(14)]
        public long? NativeBytes { get; set; }

        [Key(15)]
        public int? GcGen0Delta { get; set; }

        [Key(16)]
        public int? UnityFrame { get; set; }

        [Key(17)]
        public int? CameraTotalViewCount { get; set; }

        [Key(18)]
        public int? CameraAdditionalViewCount { get; set; }

        [Key(19)]
        public int? CameraBlendingViewCount { get; set; }

        [Key(20)]
        public int? CameraMaxStackDepthTotal { get; set; }

    }
}
