// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class DebugSocketEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 1;

        [Key(1)]
        public int MessageType { get; set; }

        [Key(2)]
        public string? RequestId { get; set; }

        [Key(3)]
        public byte[] Payload { get; set; } = System.Array.Empty<byte>();

    }
}
