// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class HierarchyNodeChangeDtoV1
    {
        [Key(0)]
        public HierarchyChangeKind ChangeKind { get; set; } = HierarchyChangeKind.Unknown;

        [Key(1)]
        public long NodeId { get; set; }

        [Key(2)]
        public long ParentId { get; set; }

        [Key(3)]
        public int TypeId { get; set; }

        [Key(4)]
        public HierarchyNodeFlags Flags { get; set; } = HierarchyNodeFlags.None;

        [Key(5)]
        public int Depth { get; set; }

        [Key(6)]
        public int SiblingIndex { get; set; }

        [Key(7)]
        public int ChildCount { get; set; }

        [Key(8)]
        public int TraversalIndex { get; set; }

        [Key(9)]
        public string Name { get; set; } = string.Empty;

        [Key(10)]
        public string? TypeName { get; set; }

    }
}
