// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;

namespace OneStarMaker.Foundation.DebugSocket
{
    [Flags]
    public enum HierarchyNodeFlags
    {
        None = 0,
        ActiveSelf = 1 << 0,
        ActiveInHierarchy = 1 << 1,
        SceneRoot = 1 << 2,
        PrefabInstance = 1 << 3,
        DontDestroyOnLoad = 1 << 4,
        HasChildren = 1 << 5,
    }
}
