// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

namespace OneStarMaker.Foundation.DebugSocket
{
    public enum HierarchyChangeKind
    {
        Unknown = 0,
        Upsert = 1,
        Remove = 2,
    }
}
