// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class HierarchyDeltaEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 1;

        [Key(1)]
        public long BaseRevision { get; set; }

        [Key(2)]
        public long Revision { get; set; }

        [Key(3)]
        public long CapturedAtUnixTimeMilliseconds { get; set; }

        [Key(4)]
        public string ScopeName { get; set; } = string.Empty;

        [Key(5)]
        public HierarchyNodeChangeDtoV1[] Changes { get; set; } = System.Array.Empty<HierarchyNodeChangeDtoV1>();

    }
}
