// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

namespace OneStarMaker.Foundation.DebugSocket
{
    public enum InspectorDetailState
    {
        Unknown = 0,
        Pending = 1,
        Ready = 2,
        NotFound = 3,
        Unsupported = 4,
        Faulted = 5,
    }
}
