// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;

namespace OneStarMaker.Foundation.DebugSocket
{
    [Flags]
    public enum InspectorQueryFlags
    {
        None = 0,
        IncludeMetadata = 1 << 0,
        IncludeComponents = 1 << 1,
        IncludeProperties = 1 << 2,
        IncludeRawValues = 1 << 3,
    }
}
