// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class InspectorSectionDtoV1
    {
        [Key(0)]
        public int SectionId { get; set; }

        [Key(1)]
        public InspectorSectionKind Kind { get; set; } = InspectorSectionKind.Unknown;

        [Key(2)]
        public int TypeId { get; set; }

        [Key(3)]
        public string DisplayName { get; set; } = string.Empty;

        [Key(4)]
        public string? TypeName { get; set; }

        [Key(5)]
        public InspectorPropertyDtoV1[] Properties { get; set; } = System.Array.Empty<InspectorPropertyDtoV1>();

    }
}
