// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.DebugSocket
{
    [MessagePackObject]
    public sealed partial class InspectorPropertyDtoV1
    {
        [Key(0)]
        public int PropertyId { get; set; }

        [Key(1)]
        public int ValueTypeId { get; set; }

        [Key(2)]
        public InspectorPropertyFlags Flags { get; set; } = InspectorPropertyFlags.None;

        [Key(3)]
        public string DisplayName { get; set; } = string.Empty;

        [Key(4)]
        public string ValueText { get; set; } = string.Empty;

        [Key(5)]
        public string? RawValue { get; set; }

        [Key(6)]
        public string? Unit { get; set; }

        [Key(7)]
        public string? Path { get; set; }

    }
}
