// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

namespace DebugStudio.Contracts.Protocol;

public enum ControlCommandRoundtripStatus
{
    Completed = 0,
    TimedOut = 1,
    Failed = 2,
}
