// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace DebugStudio.Contracts.Protocol;

[MessagePackObject]
public sealed partial class ControlCommandResponseEnvelopeV1
{
    [Key(0)]
    public string RequestId { get; set; } = string.Empty;

    [Key(1)]
    public ControlCommandRoundtripStatus Status { get; set; } = ControlCommandRoundtripStatus.Failed;

    [Key(2)]
    public string Detail { get; set; } = string.Empty;

    [Key(3)]
    public DebugCommandResultEnvelopeV1? CommandResult { get; set; }

}
