// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

namespace DebugStudio.Contracts.Protocol;

public enum DebugSocketMessageType
{
    Unknown = 0,
    Log = 1,
    Telemetry = 2,
    ServiceStatus = 3,
    DebugCommand = 4,
    CommandResult = 5,
    CapabilityHello = 6,
    CapabilityWelcome = 7,
    HierarchySnapshot = 8,
    HierarchyDelta = 9,
    InspectorQuery = 10,
    InspectorDetail = 11,
    ControlCommandRequest = 12,
    ControlCommandResponse = 13,
}
