// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;

namespace DebugStudio.Contracts.Protocol;

[Flags]
public enum DebugStudioCapability : long
{
    None = 0,
    CapabilityNegotiation = 1L << 0,
    LogStream = 1L << 1,
    TelemetryStream = 1L << 2,
    ServiceStatusStream = 1L << 3,
    DebugCommand = 1L << 4,
    CommandResult = 1L << 5,
    HierarchySnapshot = 1L << 6,
    HierarchyDelta = 1L << 7,
    InspectorQuery = 1L << 8,
    InspectorDetail = 1L << 9,
}
