// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace DebugStudio.Contracts.Protocol;

[MessagePackObject]
public sealed partial class DebugCommandEnvelopeV1
{
    [Key(0)]
    public string RequestId { get; set; } = string.Empty;

    [Key(1)]
    public string CommandType { get; set; } = string.Empty;

    [Key(2)]
    public string PayloadJson { get; set; } = string.Empty;

}
