// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace DebugStudio.Contracts.Protocol;

[MessagePackObject]
public sealed partial class HierarchySnapshotEnvelopeV1
{
    [Key(0)]
    public int SchemaVersion { get; set; } = 1;

    [Key(1)]
    public long Revision { get; set; }

    [Key(2)]
    public long CapturedAtUnixTimeMilliseconds { get; set; }

    [Key(3)]
    public string ScopeName { get; set; } = string.Empty;

    [Key(4)]
    public HierarchyNodeDtoV1[] Nodes { get; set; } = System.Array.Empty<HierarchyNodeDtoV1>();

}
