// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace DebugStudio.Contracts.Protocol;

[MessagePackObject]
public sealed partial class HierarchyNodeDtoV1
{
    [Key(0)]
    public long NodeId { get; set; }

    [Key(1)]
    public long ParentId { get; set; }

    [Key(2)]
    public int TypeId { get; set; }

    [Key(3)]
    public HierarchyNodeFlags Flags { get; set; } = HierarchyNodeFlags.None;

    [Key(4)]
    public int Depth { get; set; }

    [Key(5)]
    public int SiblingIndex { get; set; }

    [Key(6)]
    public int ChildCount { get; set; }

    [Key(7)]
    public int TraversalIndex { get; set; }

    [Key(8)]
    public string Name { get; set; } = string.Empty;

    [Key(9)]
    public string? TypeName { get; set; }

}
