// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace DebugStudio.Contracts.Protocol;

[MessagePackObject]
public sealed partial class InspectorQueryEnvelopeV1
{
    [Key(0)]
    public int SchemaVersion { get; set; } = 1;

    [Key(1)]
    public long TargetId { get; set; }

    [Key(2)]
    public InspectorQueryFlags QueryFlags { get; set; } = InspectorQueryFlags.IncludeMetadata | InspectorQueryFlags.IncludeComponents | InspectorQueryFlags.IncludeProperties;

}
