// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;

namespace DebugStudio.Contracts.Protocol;

[Flags]
public enum InspectorPropertyFlags
{
    None = 0,
    ReadOnly = 1 << 0,
    Nullable = 1 << 1,
    ExpandedByDefault = 1 << 2,
    MissingValue = 1 << 3,
}
