// <auto-generated />
// このファイルは protocol/debugsocket YAML から生成されています。
// 手編集禁止。契約を変えるときは YAML を直し、tools/protocol-codegen で再生成してください。
#nullable enable

using System;
using MessagePack;

namespace OneStarMaker.Foundation.Logging
{
    [MessagePackObject]
    public sealed partial class LogEnvelopeV1
    {
        [Key(0)]
        public int SchemaVersion { get; set; } = 1;

        [Key(1)]
        public string ApplicationName { get; set; } = string.Empty;

        [Key(2)]
        public long TimestampUnixTimeMilliseconds { get; set; }

        [Key(3)]
        public string Category { get; set; } = string.Empty;

        [Key(4)]
        public int LogLevel { get; set; }

        [Key(5)]
        public int EventId { get; set; }

        [Key(6)]
        public string? EventName { get; set; }

        [Key(7)]
        public string Message { get; set; } = string.Empty;

        [Key(8)]
        public string? Exception { get; set; }

        [Key(9)]
        public int ThreadId { get; set; }

        [Key(10)]
        public string? ThreadName { get; set; }

        [Key(11)]
        public string? MemberName { get; set; }

        [Key(12)]
        public string? FilePath { get; set; }

        [Key(13)]
        public int LineNumber { get; set; }

        [Key(14)]
        public string SessionId { get; set; } = string.Empty;

        [Key(15)]
        public long ProducerSequence { get; set; }

        [Key(16)]
        public int? UnityFrameAtEmit { get; set; }

        [Key(17)]
        public long? TraceId { get; set; }

        [Key(18)]
        public long? SpanId { get; set; }

    }
}
